// import 'package:flutter/material.dart';
// import 'package:s2_international/utils/utilities.dart';

// class RatesScreen extends StatelessWidget {
//   final Map rates = {
//     "Afghanistan (AF)": "10p",
//     "Åland Islands (AX)",
//     "Albania (AL)": "29p",
//     "Algeria (DZ)": "",
//     "American Samoa (AS)",
//     "Andorra (AD)": "10p",
//     "Angola (AO)": "12p",
//     "Anguilla (AI)": "15p",
//     "Antarctica (AQ)",
//     "Antigua & Barbuda (AG)" :"13p",
//     "Argentina (AR)": "10p",
//     "Armenia (AM)": "15p",
//     "Aruba (AW)": "11.5p",
//     "Australia (AU)": "4p",
//     "Austria (AT)": "4.5p",
//     "Azerbaijan (AZ)": "20p",
//     "Bahamas (BS)": "8p",
//     "Bahrain (BH)": "8p",
//     "Bangladesh (BD)" : "1.9p",
//     "Barbados (BB)": "15p",
//     "Belarus (BY)" :"24p",
//     "Belgium (BE)" :"5p",
//     "Belize (BZ)" :"1.4",
//     "Benin (BJ)": "22p",
//     "Bermuda (BM)": "3p",
//     "Bhutan (BT)": "5p",
//     "Bolivia (BO)": "9p",
//     "Bosnia & Herzegovina (BA)": "28p",
//     "Botswana (BW)",
//     "Bouvet Island (BV)",
//     "Brazil (BR)": "3p",
//     "British Indian Ocean Territory (IO)",
//     "British Virgin Islands (VG)",
//     "Brunei (BN)": "2p",
//     "Bulgaria (BG)": "14p",
//     "Burkina Faso (BF)": "17.5p",
//     "Burundi (BI)": "32p",
//     "Cambodia (KH)": "3.5p",
//     "Cameroon (CM)",
//     "Canada (CA)",
//     "Cape Verde (CV)",
//     "Caribbean Netherlands (BQ)",
//     "Cayman Islands (KY)",
//     "Central African Republic (CF)",
//     "Chad (TD)",
//     "Chile (CL)",
//     "China (CN)",
//     "Christmas Island (CX)",
//     "Cocos (Keeling) ,Islands (CC)",
//     "Colombia (CO)",
//     "Comoros (KM)",
//     "Congo - Brazzaville (CG)",
//     "Congo - Kinshasa (CD)",
//     "Cook Islands (CK)",
//     "Costa Rica (CR)",
//     "Côte d’Ivoire (CI)",
//     "Croatia (HR)",
//     "Cuba (CU)",
//     "Curaçao (CW)",
//     "Cyprus (CY)",
//     "Czechia (CZ)",
//     "Denmark (DK)",
//     "Djibouti (DJ)",
//     "Dominica (DM)",
//     "Dominican Republic (DO)",
//     "Ecuador (EC)",
//     "Egypt (EG)",
//     "El Salvador (SV)",
//     "Equatorial Guinea (GQ)",
//     "Eritrea (ER)",
//     "Estonia (EE)",
//     "Eswatini (SZ)",
//     "Ethiopia (ET)",
//     "Falkland Islands (FK)",
//     "Faroe Islands (FO)",
//     "Fiji (FJ)",
//     "Finland (FI)",
//     "France (FR)",
//     "French Guiana (GF)",
//     "French Polynesia (PF)",
//     "French Southern Territories (TF)",
//     "Gabon (GA)": "26p",
//     "Gambia (GM)": "46p",
//     "Georgia (GE)": "18p",
//     "Germany (DE)": "4.5",
//     "Ghana (GH)": "17p",
//     "Gibraltar (GI)": "19p",
//     "Greece (GR)": "4.5p",
//     "Greenland (GL)": "32.5p",
//     "Grenada (GD)": "16p",
//     "Guadeloupe (GP)",
//     "Guam (GU)" :"1p",
//     "Guatemala (GT)": "8p",
//     "Guernsey (GG)": "",
//     "Guinea (GN)": "30p",
//     "Guinea-Bissau (GW)": "40p",
//     "Guyana (GY)": "14.5",
//     "Haiti (HT)": "20p",
//     "Heard & McDonald Islands (HM)",
//     "Honduras (HN)": "7.5p",
//     "Hong Kong SAR China (HK)": "1.5p",
//     "Hungary (HU)": "3.5p",
//     "Iceland (IS)" : "2.5p",
//     "India (IN)": "1.1p",
//     "Indonesia (ID)": "3p",
//     "Iran (IR)" :"13p",
//     "Iraq (IQ)": "15p",
//     "Ireland (IE)",
//     "Isle of Man (IM)",
//     "Israel (IL)",
//     "Italy (IT)",
//     "Jamaica (JM)",
//     "Japan (JP)",
//     "Jersey (JE)",
//     "Jordan (JO)",
//     "Kazakhstan (KZ)",
//     "Kenya (KE)",
//     "Kiribati (KI)",
//     "Kuwait (KW)",
//     "Kyrgyzstan (KG)",
//     "Laos (LA)",
//     "Latvia (LV)",
//     "Lebanon (LB)",
//     "Lesotho (LS)",
//     "Liberia (LR)",
//     "Libya (LY)",
//     "Liechtenstein (LI)",
//     "Lithuania (LT)",
//     "Luxembourg (LU)",
//     "Macao SAR China (MO)",
//     "Madagascar (MG)",
//     "Malawi (MW)",
//     "Malaysia (MY)",
//     "Maldives (MV)",
//     "Mali (ML)",
//     "Malta (MT)",
//     "Marshall Islands (MH)",
//     "Martinique (MQ)",
//     "Mauritania (MR)",
//     "Mauritius (MU)",
//     "Mayotte (YT)",
//     "Mexico (MX)",
//     "Micronesia (FM)",
//     "Moldova (MD)",
//     "Monaco (MC)",
//     "Mongolia (MN)",
//     "Montenegro (ME)",
//     "Montserrat (MS)",
//     "Morocco (MA)",
//     "Mozambique (MZ)",
//     "Myanmar (Burma) ,(MM)",
//     "Namibia (NA)",
//     "Nauru (NR)",
//     "Nepal (NP)",
//     "Netherlands (NL)",
//     "New Caledonia (NC)",
//     "New Zealand (NZ)",
//     "Nicaragua (NI)",
//     "Niger (NE)",
//     "Nigeria (NG)",
//     "Niue (NU)",
//     "Norfolk Island (NF)",
//     "North Korea (KP)",
//     "North Macedonia (MK)",
//     "Northern Mariana Islands (MP)",
//     "Norway (NO)",
//     "Oman (OM)",
//     "Pakistan (PK)",
//     "Palau (PW)",
//     "Palestinian Territories (PS)",
//     "Panama (PA)",
//     "Papua New Guinea (PG)",
//     "Paraguay (PY)",
//     "Peru (PE)",
//     "Philippines (PH)",
//     "Pitcairn Islands (PN)",
//     "Poland (PL)",
//     "Portugal (PT)",
//     "Puerto Rico (PR)",
//     "Qatar (QA)",
//     "Réunion (RE)",
//     "Romania (RO)",
//     "Russia (RU)",
//     "Rwanda (RW)",
//     "Samoa (WS)",
//     "San Marino (SM)",
//     "São Tomé & Príncipe (ST)",
//     "Saudi Arabia (SA)",
//     "Senegal (SN)",
//     "Serbia (RS)",
//     "Seychelles (SC)",
//     "Sierra Leone (SL)",
//     "Singapore (SG)",
//     "Sint Maarten (SX)",
//     "Slovakia (SK)",
//     "Slovenia (SI)",
//     "Solomon Islands (SB)",
//     "Somalia (SO)",
//     "South Africa (ZA)",
//     "South Georgia & South Sandwich Islands (GS)",
//     "South Korea (KR)",
//     "South Sudan (SS)",
//     "Spain (ES)",
//     "Sri Lanka (LK)",
//     "St. Barthélemy (BL)",
//     "St. Helena (SH)",
//     "St. Kitts & Nevis (KN)",
//     "St. Lucia (LC)",
//     "St. Martin (MF)",
//     "St. Pierre & Miquelon (PM)",
//     "St. Vincent & Grenadines (VC)",
//     "Sudan (SD)",
//     "Suriname (SR)",
//     "Svalbard & Jan Mayen (SJ)",
//     "Sweden (SE)",
//     "Switzerland (CH)",
//     "Syria (SY)",
//     "Taiwan (TW)",
//     "Tajikistan (TJ)",
//     "Tanzania (TZ)",
//     "Thailand (TH)",
//     "Timor-Leste (TL)",
//     "Togo (TG)",
//     "Tokelau (TK)",
//     "Tonga (TO)",
//     "Trinidad & Tobago (TT)",
//     "Tunisia (TN)",
//     "Turkey (TR)",
//     "Turkmenistan (TM)",
//     "Turks & Caicos Islands (TC)",
//     "Tuvalu (TV)",
//     "U.S. Outlying Islands (UM)",
//     "U.S. Virgin Islands (VI)",
//     "Uganda (UG)",
//     "Ukraine (UA)",
//     "United Arab Emirates (AE)",
//     "United Kingdom (GB)",
//     "United States (US)",
//     "Uruguay (UY)",
//     "Uzbekistan (UZ)",
//     "Vanuatu (VU)",
//     "Vatican City (VA)",
//     "Venezuela (VE)",
//     "Vietnam (VN)",
//     "Wallis & Futuna (WF)",
//     "Western Sahara (EH)",
//     "Yemen (YE)",
//     "Zambia (ZM)",
//     "Zimbabwe (ZW)",
//   };

//   @override
//   Widget build(BuildContext context) {
//     var WIDTH = MediaQuery.of(context).size.width;
//     List<Widget> widgets = rates.map((name) => new Text(name)).toList();
//     return Scaffold(
//       appBar: AppBar(
//         elevation: 0.0,
//         backgroundColor: Colors.white,
//         title: const Text(
//           'Rates',
//           style: TextStyle(
//             color: Colors.black,
//             fontSize: 18,
//             fontWeight: FontWeight.bold,
//           ),
//         ),
//       ),
//       body: Stack(
//         children: [
//           Align(
//             alignment: Alignment.centerLeft,
//             child: CustomPaint(
//               size: Size(
//                   WIDTH,
//                   (WIDTH * 1.525)
//                       .toDouble()), //You can Replace [WIDTH] with your desired width for Custom Paint and height will be calculated automatically
//               painter: RPSCustomPainter(),
//             ),
//           ),
//           Padding(
//             padding: const EdgeInsets.all(8.0),
//             child: ListView(children: [
//               ...rates
//                   .map(
//                     (item) => ListTile(
//                       title: Text(
//                         item,
//                         style: TextStyle(
//                           color: Colors.black,
//                           fontSize: 18,
//                         ),
//                       ),
//                     ),
//                   )
//                   .toList(),
//             ]),
//           ),
//         ],
//       ),
//     );
//   }
// }

// class RPSCustomPainter extends CustomPainter {
//   @override
//   void paint(Canvas canvas, Size size) {
//     Paint paint_0 = new Paint()
//       ..color = Colors.blue[50]
//       ..style = PaintingStyle.fill
//       ..strokeWidth = 1;

//     Path path_0 = Path();
//     path_0.moveTo(0, size.height * 0.0040000);
//     path_0.quadraticBezierTo(size.width * 0.4931250, size.height * 0.1015000,
//         size.width * 0.5000000, size.height * 0.4980000);
//     path_0.quadraticBezierTo(size.width * 0.5009375, size.height * 0.9030000,
//         size.width * 0.0012500, size.height * 0.9980000);
//     path_0.cubicTo(
//         size.width * 0.0015625,
//         size.height * 0.7485000,
//         size.width * -0.0034375,
//         size.height * 0.7505000,
//         0,
//         size.height * 0.0040000);
//     path_0.close();

//     canvas.drawPath(path_0, paint_0);
//   }

//   @override
//   bool shouldRepaint(covariant CustomPainter oldDelegate) {
//     return true;
//   }
// }
